/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddServiceCommand model module.
 * @module model/AddServiceCommand
 * @version v0
 */
class AddServiceCommand {
    /**
     * Constructs a new <code>AddServiceCommand</code>.
     * @alias module:model/AddServiceCommand
     * @param name {String} 
     * @param description {String} 
     * @param durationMinutes {Number} 
     * @param price {Number} 
     */
    constructor(name, description, durationMinutes, price) { 
        
        AddServiceCommand.initialize(this, name, description, durationMinutes, price);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, durationMinutes, price) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['durationMinutes'] = durationMinutes;
        obj['price'] = price;
    }

    /**
     * Constructs a <code>AddServiceCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddServiceCommand} obj Optional instance to populate.
     * @return {module:model/AddServiceCommand} The populated <code>AddServiceCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddServiceCommand();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('durationMinutes')) {
                obj['durationMinutes'] = ApiClient.convertToType(data['durationMinutes'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddServiceCommand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddServiceCommand</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddServiceCommand.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

AddServiceCommand.RequiredProperties = ["name", "description", "durationMinutes", "price"];

/**
 * @member {String} name
 */
AddServiceCommand.prototype['name'] = undefined;

/**
 * @member {String} description
 */
AddServiceCommand.prototype['description'] = undefined;

/**
 * @member {Number} durationMinutes
 */
AddServiceCommand.prototype['durationMinutes'] = undefined;

/**
 * @member {Number} price
 */
AddServiceCommand.prototype['price'] = undefined;






export default AddServiceCommand;

