/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchServiceCommand model module.
 * @module model/PatchServiceCommand
 * @version v0
 */
class PatchServiceCommand {
    /**
     * Constructs a new <code>PatchServiceCommand</code>.
     * @alias module:model/PatchServiceCommand
     * @param serviceId {Number} 
     */
    constructor(serviceId) { 
        
        PatchServiceCommand.initialize(this, serviceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serviceId) { 
        obj['serviceId'] = serviceId;
    }

    /**
     * Constructs a <code>PatchServiceCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchServiceCommand} obj Optional instance to populate.
     * @return {module:model/PatchServiceCommand} The populated <code>PatchServiceCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchServiceCommand();

            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('durationMinutes')) {
                obj['durationMinutes'] = ApiClient.convertToType(data['durationMinutes'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchServiceCommand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchServiceCommand</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PatchServiceCommand.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

PatchServiceCommand.RequiredProperties = ["serviceId"];

/**
 * @member {Number} serviceId
 */
PatchServiceCommand.prototype['serviceId'] = undefined;

/**
 * @member {String} name
 */
PatchServiceCommand.prototype['name'] = undefined;

/**
 * @member {String} description
 */
PatchServiceCommand.prototype['description'] = undefined;

/**
 * @member {Number} durationMinutes
 */
PatchServiceCommand.prototype['durationMinutes'] = undefined;

/**
 * @member {Number} price
 */
PatchServiceCommand.prototype['price'] = undefined;






export default PatchServiceCommand;

