/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchUserStatusCommand model module.
 * @module model/PatchUserStatusCommand
 * @version v0
 */
class PatchUserStatusCommand {
    /**
     * Constructs a new <code>PatchUserStatusCommand</code>.
     * @alias module:model/PatchUserStatusCommand
     * @param userId {Number} 
     * @param userStatus {module:model/PatchUserStatusCommand.UserStatusEnum} 
     */
    constructor(userId, userStatus) { 
        
        PatchUserStatusCommand.initialize(this, userId, userStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, userStatus) { 
        obj['userId'] = userId;
        obj['userStatus'] = userStatus;
    }

    /**
     * Constructs a <code>PatchUserStatusCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchUserStatusCommand} obj Optional instance to populate.
     * @return {module:model/PatchUserStatusCommand} The populated <code>PatchUserStatusCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchUserStatusCommand();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('userStatus')) {
                obj['userStatus'] = ApiClient.convertToType(data['userStatus'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchUserStatusCommand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchUserStatusCommand</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PatchUserStatusCommand.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['userStatus'] && !(typeof data['userStatus'] === 'string' || data['userStatus'] instanceof String)) {
            throw new Error("Expected the field `userStatus` to be a primitive type in the JSON string but got " + data['userStatus']);
        }

        return true;
    }


}

PatchUserStatusCommand.RequiredProperties = ["userId", "userStatus"];

/**
 * @member {Number} userId
 */
PatchUserStatusCommand.prototype['userId'] = undefined;

/**
 * @member {module:model/PatchUserStatusCommand.UserStatusEnum} userStatus
 */
PatchUserStatusCommand.prototype['userStatus'] = undefined;





/**
 * Allowed values for the <code>userStatus</code> property.
 * @enum {String}
 * @readonly
 */
PatchUserStatusCommand['UserStatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "SUSPENDED"
     * @const
     */
    "SUSPENDED": "SUSPENDED"
};



export default PatchUserStatusCommand;

