/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterUserResponseDto model module.
 * @module model/RegisterUserResponseDto
 * @version v0
 */
class RegisterUserResponseDto {
    /**
     * Constructs a new <code>RegisterUserResponseDto</code>.
     * @alias module:model/RegisterUserResponseDto
     */
    constructor() { 
        
        RegisterUserResponseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegisterUserResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterUserResponseDto} obj Optional instance to populate.
     * @return {module:model/RegisterUserResponseDto} The populated <code>RegisterUserResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterUserResponseDto();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('userStatus')) {
                obj['userStatus'] = ApiClient.convertToType(data['userStatus'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegisterUserResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegisterUserResponseDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['userStatus'] && !(typeof data['userStatus'] === 'string' || data['userStatus'] instanceof String)) {
            throw new Error("Expected the field `userStatus` to be a primitive type in the JSON string but got " + data['userStatus']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }

        return true;
    }


}



/**
 * @member {String} username
 */
RegisterUserResponseDto.prototype['username'] = undefined;

/**
 * @member {module:model/RegisterUserResponseDto.UserStatusEnum} userStatus
 */
RegisterUserResponseDto.prototype['userStatus'] = undefined;

/**
 * @member {module:model/RegisterUserResponseDto.RoleEnum} role
 */
RegisterUserResponseDto.prototype['role'] = undefined;





/**
 * Allowed values for the <code>userStatus</code> property.
 * @enum {String}
 * @readonly
 */
RegisterUserResponseDto['UserStatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "SUSPENDED"
     * @const
     */
    "SUSPENDED": "SUSPENDED"
};


/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
RegisterUserResponseDto['RoleEnum'] = {

    /**
     * value: "CLIENT"
     * @const
     */
    "CLIENT": "CLIENT",

    /**
     * value: "EMPLOYEE"
     * @const
     */
    "EMPLOYEE": "EMPLOYEE",

    /**
     * value: "PRESIDENT"
     * @const
     */
    "PRESIDENT": "PRESIDENT"
};



export default RegisterUserResponseDto;

