/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LoginUserCommand from '../model/LoginUserCommand';
import RegisterUserCommand from '../model/RegisterUserCommand';
import RegisterUserResponseDto from '../model/RegisterUserResponseDto';

/**
* AuthController service.
* @module api/AuthControllerApi
* @version v0
*/
export default class AuthControllerApi {

    /**
    * Constructs a new AuthControllerApi. 
    * @alias module:api/AuthControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the login operation.
     * @callback module:api/AuthControllerApi~loginCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/LoginUserCommand} loginUserCommand 
     * @param {module:api/AuthControllerApi~loginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    login(loginUserCommand, callback) {
      let postBody = loginUserCommand;
      // verify the required parameter 'loginUserCommand' is set
      if (loginUserCommand === undefined || loginUserCommand === null) {
        throw new Error("Missing the required parameter 'loginUserCommand' when calling login");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the registerUser operation.
     * @callback module:api/AuthControllerApi~registerUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RegisterUserResponseDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/RegisterUserCommand} registerUserCommand 
     * @param {module:api/AuthControllerApi~registerUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RegisterUserResponseDto}
     */
    registerUser(registerUserCommand, callback) {
      let postBody = registerUserCommand;
      // verify the required parameter 'registerUserCommand' is set
      if (registerUserCommand === undefined || registerUserCommand === null) {
        throw new Error("Missing the required parameter 'registerUserCommand' when calling registerUser");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = RegisterUserResponseDto;
      return this.apiClient.callApi(
        '/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
